-- Seed songs with YouTube links
INSERT INTO songs (title, artist, key, tempo, resource_url, status) VALUES
('Seven Nation Army', 'The White Stripes', 'E Minor', '124 BPM', 'https://www.youtube.com/watch?v=0J2QdDbelmY', 'active'),
('Mr. Brightside', 'The Killers', 'Db Major', '148 BPM', 'https://www.youtube.com/watch?v=gGdGFtwCNBE', 'active'),
('Smells Like Teen Spirit', 'Nirvana', 'F Minor', '117 BPM', 'https://www.youtube.com/watch?v=hTWKbfoikeg', 'active'),
('Sweet Child O'' Mine', 'Guns N'' Roses', 'Db Major', '125 BPM', 'https://www.youtube.com/watch?v=1w7OgIMMRc4', 'active'),
('Enter Sandman', 'Metallica', 'E Minor', '123 BPM', 'https://www.youtube.com/watch?v=CD-E-LDc384', 'active'),
('Wonderwall', 'Oasis', 'F# Minor', '87 BPM', 'https://www.youtube.com/watch?v=6hzrDeceEKc', 'active'),
('Hotel California', 'Eagles', 'B Minor', '74 BPM', 'https://www.youtube.com/watch?v=EqPtz5qN7HM', 'active'),
('Basket Case', 'Green Day', 'Eb Major', '175 BPM', 'https://www.youtube.com/watch?v=NUTGr5t3MoY', 'active'),
('Under the Bridge', 'Red Hot Chili Peppers', 'E Major', '84 BPM', 'https://www.youtube.com/watch?v=GLvohMXgcBo', 'active'),
('Everlong', 'Foo Fighters', 'D Major', '158 BPM', 'https://www.youtube.com/watch?v=eBG7P-K-r1Y', 'active'),
('Creep', 'Radiohead', 'G Major', '92 BPM', 'https://www.youtube.com/watch?v=XFkzRNyygfk', 'active'),
('Black Hole Sun', 'Soundgarden', 'F Major', '106 BPM', 'https://www.youtube.com/watch?v=3mbBbFH9fAg', 'active'),
('The Pretender', 'Foo Fighters', 'A Minor', '173 BPM', 'https://www.youtube.com/watch?v=SBjQ9tuuTJQ', 'active'),
('Plush', 'Stone Temple Pilots', 'Eb Major', '144 BPM', 'https://www.youtube.com/watch?v=V5UOC0C0x8Q', 'active'),
('Come as You Are', 'Nirvana', 'E Minor', '120 BPM', 'https://www.youtube.com/watch?v=vabnZ9-ex7o', 'active'),
('By the Way', 'Red Hot Chili Peppers', 'F Major', '122 BPM', 'https://www.youtube.com/watch?v=JnfyjwChuNU', 'active'),
('Song 2', 'Blur', 'Ab Major', '130 BPM', 'https://www.youtube.com/watch?v=SSbBvKaM6sk', 'active'),
('Chop Suey!', 'System of a Down', 'G Minor', '127 BPM', 'https://www.youtube.com/watch?v=CSvFpBOe8eY', 'active'),
('Killing in the Name', 'Rage Against the Machine', 'D Minor', '89 BPM', 'https://www.youtube.com/watch?v=bWXazVhlyxQ', 'active'),
('No One Knows', 'Queens of the Stone Age', 'C Minor', '171 BPM', 'https://www.youtube.com/watch?v=s88r_q7oufE', 'active'),
('Kryptonite', '3 Doors Down', 'B Minor', '99 BPM', 'https://www.youtube.com/watch?v=xPU8OAjjS4k', 'active'),
('Given to Fly', 'Pearl Jam', 'G Major', '110 BPM', 'https://www.youtube.com/watch?v=1d9776vL104', 'active'),
('Interstate Love Song', 'Stone Temple Pilots', 'C# Minor', '83 BPM', 'https://www.youtube.com/watch?v=yjJL9DGU7Gg', 'active'),
('Boulevard of Broken Dreams', 'Green Day', 'F Minor', '83 BPM', 'https://www.youtube.com/watch?v=Soa3gO7tL-c', 'active'),
('All The Small Things', 'Blink-182', 'C Major', '149 BPM', 'https://www.youtube.com/watch?v=9Ht5RZpzPqw', 'active');
